src/configs/toast/toastMessageProps.tsx, src/screens/StudentIdScreen.tsx, src/utils/getCurrentTime.ts
- 포털 학번이 잘못 긁혀오는 현상이 있어, 학생증 Qr 코드를 임시적으로 블록 처리합니다. 
- QR과 관련된 코드들을 블록 처리했습니다.
- QR 코드 및 페이코 버튼이 사라짐에 따라, 스크린 상단 패딩값을 조절했습니다.
- Toast 메시지를 추가했습니다.
- close #307
=> [App-265] 학생증 QR 코드 코드 블록 처리

src/components/molecules/screens/announcement/detail/AnnouncementHTML.tsx, src/navigators/RootStackNavigator.tsx
- 안드로이드에서 특정 공지글 진입 시 앱이 강제종료되는 현상을 해결했습니다.
- 확인된 바로는 표(table)이 있는 공지글에서 발생하는 현상이었습니다.
- `react-native-render-html`과 `@native-html/table-plugin` 두 라이브러리를 사용하는데, 해당 조합에서 발생하는 [버그](https://github.com/meliorence/react-native-render-html/issues/393)입니다.
- `HTML(imported from 'react-native-render-html')` 컴포넌트에 특정한 prop을 추가함으로서 간단히(검색에 들인 시간과 비교했을 때 매우..) 해결되는 문제였습니다.
```tsx
<HTML 
// with some other props..
renderersProps={{
table: {
webViewProps: {
style: {opacity: 0.99},
},
},
}}
/>
````
- 에러가 무슨 이유로 발생하는지 파악하지 못하였습니다. 그에 따라 저 스타일과 관련된 것으로만 보이는 코드가 어떻게 이 에러를 해결하는지도 알 수가 없었습니다.
- 원리를 파악하려면 해당 라이브러리 소스, 심하면 native level까지 뜯어보아야 하는 것으로 보여, 도저히 그렇게 할 엄두는 내지 못했습니다. 그닥 효율적인 방법도 아닌 것 같아서 일단 이대로 두는 게 최선으로 보입니다.
- rebuild 배포 후에, UX에 큰 해악을 끼치는 에러를 너무 오래 방치해 두었다는 생각이 듭니다. 다음에는 신경써서 신속하게 고칠 수 있도록 하겠습니다. …
=> [APP-254] 공지글 보기 진입 시 강제종료되는 현상 대응

src/screens/LibraryRecapScreen.tsx
- Android에서 webview와 앱 간 통신이 안되는 문제를 해결했습니다.
- userAgent속성에 platform정보를 넘겨주고, @uoslife/webview에서 대응합니다.
- useAndroidBackPress훅을 적용 해제했습니다.
close #310
=> [APP-266] Android에서 웹앱간 통신이 안되는 문제

src/api/core/methods.ts, src/api/services/core/verification/verificationAPI.interface.ts, src/api/services/core/verification/verificationAPI.ts, src/api/services/core/verification/verificationAPI.type.ts, src/configs/toast/toastMessageProps.tsx, src/navigators/MyPageStackNavigator.tsx, src/screens/myPage/profile/MypageProfileScreen.tsx, src/screens/myPage/profile/PortalAuthenticationManagementScreen.tsx
- 수정된 포털 연동 API 스펙을 반영했습니다.
- 포털연동을 관리하는 '포털연동관리페이지'를 작성하고, 구현했습니다.
- 해당 페이지에서 유저는 '자신의 신분'을 선택 후 업데이트할 수 있고, '포털연동해지'를 할 수 있습니다.
- react native navigation의 'Mypage_changeNickname' params 값에서 type 오류가 발생했기 때문에, isMyPage 타입을 추가하여 해결했습니다.
- close #315
=> [APP-268] 수정된 포털연동 API 반영

package.json, src/components/molecules/screens/library/LibararySeatStatus.tsx, src/components/molecules/screens/library/LibraryUserInfo.tsx, src/components/molecules/screens/main/contents/CafeteriaContents.tsx, src/components/molecules/screens/main/contents/LibraryContents.tsx, src/screens/MainScreen.tsx, src/screens/library/LibraryScreen.tsx, src/store/library/index.ts, yarn.lock
- 기존 API fetching 코드를 react query로 마이그레이션 합니다.
- getLibraryReservation API 호출을 jotai-tanstack-query를 이용하도록 변경했습니다.
- 도서관 화면이 Focus 될 경우 auto refetch되도록, isFocusedLibraryAtom로 focused 상태를 관리합니다. 
- refetchInterval 시간은 5초입니다.
- close #322
=> [APP-272] 기존 fetching 코드를 react query로 마이그레이션

src/configs/api.ts
- ky apiClient의 defaultOptions을 수정했습니다. 변경 사항은 아래와 같습니다.
```typescript
DEFAULT_API_TIMEOUT // 10초 > 3초
DEFAULT_API_RETRY_BACKOFFLIMIT// 3초 > 1초
``` 
close #366
=> [RN-15] API 호출시 timeout 및 retry 시간 수정

src/components/molecules/common/GuidePopup.tsx, src/screens/library/main_screen/MySeatScreen.tsx
- 도서관 안내 메시지 팝업을 추가했습니다
- useModal을 이용하여 기존 modal과 동일하게 동작합니다. 
- 추후에 시대생 라이브러리 로고 업로드 이후에 로고 수정하겠습니다.
- 기존에 있던 [RN-29]도서관 정보 모달과 [RN-31]도서관 정보 토스트 브랜치 삭제가 필요합니다.
=> [RN-35] 도서관 안내 메시지 팝업 추가

src/screens/account/common/SetNicknameScreen.tsx
- 닉네임 변경 페이지에서 '변경하기' 버튼 클릭시 하단 모달이 표시되지 않도록 수정했습니다.
close #412
=> [RN-42] 닉네임 변경시 하단 모달 뜨지 않도록 수정

src/components/molecules/screens/main/contents/LibraryContents.tsx, src/screens/MainScreen.tsx, src/screens/library/room_status/LibrarySeatingChartScreen.tsx
- 메인페이지의 '좌석 현황 보기' 버튼 클릭시 도서관 좌석 페이지로 이동하도록 동작을 수정했습니다.
close #409
=> [RN-40] '좌석 현황 보기' 버튼 클릭시 도서관 좌석 페이지로 이동

src/api/services/util/library/libraryAPI.interface.ts, src/api/services/util/library/libraryAPI.ts, src/api/services/util/library/libraryAPI.type.ts, src/components/molecules/common/GuidePopup.tsx, src/components/molecules/screens/library/LibrarySeatingChart.tsx, src/components/molecules/screens/library/main/my_seat/LibraryCircleTimer.tsx, src/components/molecules/screens/library/main/my_seat/LibraryCircleTimerContents.tsx, src/components/molecules/screens/library/main/my_seat/LibrarySeatControl.tsx, src/components/molecules/screens/library/main/my_seat/LibraryUserInfo.tsx, src/components/molecules/screens/library/ranking/LibraryRanking.tsx, src/configs/deepLinking.ts, src/configs/toast/toastMessageProps.tsx, src/navigators/LibraryStackNavigator.tsx, src/navigators/types/library.ts, src/screens/library/LibraryMainScreen.tsx, src/screens/library/main_screen/MySeatScreen.tsx, src/screens/library/room_status/LibrarySeatingChartScreen.tsx, src/screens/library/useLibraryExtend.ts, src/screens/library/useLibraryReturn.ts, src/utils/library/findSeatItem.ts, src/utils/library/libraryRanking.ts, src/utils/library/showLibraryErrorCode.ts
- 도서관 좌석 조회 및 예약, 반납 API를 추가 및 적용했습니다.
- 좌석 반납 및 연장 모달을 BottomSheet로 변경했습니다.
- 더불어 레이아웃이 tab screen 부모에 종속되는 문제가 있어 부득이하게 모달 컴포넌트를 최상단으로 옮기고, 관련 API를 hook으로 분리했습니다.
- 도서관 관련 에러 응답 코드를 에러 메세지와 함께 대응했습니다. 해당 에러 응답 코드는 [노션 링크](https://www.notion.so/6f9ce880b8ff4a318815a8450d33112c?pvs=4)에서 보실 수 있습니다.
close #420
=> [RN-45] 도서관 예약 API 연결

src/App.tsx, src/configs/sentry.ts
- Sentry의 sample rate를 0.8으로 조절했습니다.
close #368
=> [RN-16] Sentry의 sample rate 조절

src/components/molecules/common/select/Select.tsx, src/components/molecules/common/tab_view/TabView.tsx, src/components/molecules/screens/library/LibraryChallengeBoard.tsx, src/components/molecules/screens/library/LibraryChallengeItem.tsx, src/components/molecules/screens/library/main/my_seat/LibrarySeatControl.tsx, src/components/molecules/screens/library/ranking/LibraryRanking.tsx, src/components/molecules/screens/main/contents/LibraryContents.tsx, src/configs/utility/libraryRanking/libraryRanking.ts, src/screens/library/LibraryMainScreen.tsx, src/screens/library/main_screen/ChallengeScreen.tsx, src/screens/library/room_status/LibrarySeatingChartScreen.tsx, src/screens/thirdTab/EventScreen.tsx, src/services/notification.ts, src/services/utility.ts
- 도서관 TF 배포 후 발생한 오류를 수정하고, 개선사항을 개선했습니다.
- 도서관 순위 > Select 토글이 [뒤에 뜨고](https://uoslifeteam.slack.com/archives/C06SXE98G4X/p1713872846037129), 스크롤 되지 않는 [현상](https://uoslifeteam.slack.com/archives/C06JYQS3Z4J/p1713869267635259)을 수정했습니다.
- Select 토글에 경제학부 옵션을 [추가](https://uoslifeteam.slack.com/archives/C06SXE98G4X/p1713869897298269)했습니다.
- 이벤트 페이지 이벤트 마감일을 31일 > 30일로 [수정](https://uoslifeteam.slack.com/archives/C06SXE98G4X/p1713894946006969)했습니다.
- 도서관 메인 > 내자리의 연장하기, 반납하기 버튼 간격을 [수정](https://uoslifeteam.slack.com/archives/C06SXE98G4X/p1713872092750939)했습니다.
- 도전과제 > 시간 버튼 클릭시 이전의 이미지와 상태도 확인 가능하도록 [기능을 추가](https://uoslifeteam.slack.com/archives/C06SXE98G4X/p1713871078245079) 했습니다.
이용중이지만, 이용중인 좌석이 표시되지 않는 현상을 [수정](https://uoslifeteam.slack.com/archives/C06JYQS3Z4J/p1713872541637399)했습니다.
- …
=> [RN-52] 도서관 TF 배포 후 오류 수정

src/api/services/core/libraryHistory/libraryHistoryAPI.type.ts, src/components/molecules/screens/library/LibraryUsageHistory.tsx
- 2024 이용내역 서비스 API의 서버와 클라이언트의 변수명이 달라 앱이 튕기는 현상을 수정했습니다.
close #456
=> [RN-62] 2024 이용내역 접근시 앱이 튕기는 현상

src/components/molecules/screens/main/contents/LibraryContents.tsx
- 메인페이지의 도서관 reservation API 호출시 무한 refetch되는 현상을 수정했습니다.
- API 호출을 할때 `useFocusEffect` 대신, `useIsFocuesd` 훅을 이용해 구현했습니다.
close #463
=> [RN-66] 메인페이지에서 도서관 API가 무한 refetch 하는 현상 #463

src/screens/StudentIdScreen.tsx, src/screens/mypage/profile/MypageProfileScreen.tsx, src/screens/mypage/profile/PortalAuthenticationManagementScreen.tsx
- 학생증 정보 화면의 변수명을 마이그레이션된 account api 변수명에 대응했습니다.
- 포털 계정 정보에 identity.type, identity.university도 보여주도록 수정했습니다.
close #466
=> [RN-67] 학생증 정보의 변수명 수정

src/api/core/client.ts, src/api/services/account/auth/authAPI.ts
- 토큰 재발급 API의 base client를 변경하여 로그인 유지가 되지 않는 현상을 수정했습니다.
close #471
=> [RN-70] 로그인 유지가 안되는 현상 수정

src/store/app/supabaseConfig.ts
- 앱 최신버전 확인 로직을 OS별로 분리했습니다.
`app.version.latest.ios`, `app.version.latest.android`
close #484
=> [RN-76] 앱 최신버전 확인 로직을 OS별로 분리

ios/uoslife.xcodeproj/project.pbxproj, src/App.tsx, src/api/services/account/type/index.ts, src/configs/app/update_guide.ts, src/hooks/useAppStateForeground.ts, src/hooks/useInitApp.ts, src/hooks/useIsLoggedInListner.ts, src/hooks/useOpenDeeplink.ts, src/navigators/RootStackNavigator.tsx, src/services/notification.ts, src/services/user.ts, src/store/app/supabaseConfig.ts, src/utils/app/guideUpdate.ts, src/utils/app/handleFCMTokenBackground.ts, src/utils/storeToken.ts
- 앱 초기 로딩시간을 개선하고, 리팩터링을 진행했습니다.
- supabase config를 가져오는 API를 AppState가 foreground일 때 refetch해오도록 구현했습니다.
- iOS 환경에서 UOSLIFE-Dev target의 bundle identifier를 `com.beyondconnect.uoslife`에서 `com.beyondconnect.uoslife.alpha`로 변경했습니다.
- 초기 로딩 시간에서 오래걸리는 FCM Token을 가져오는 동작을, 앱 로딩 완료 후 background에서 처리하도록 분리했습니다.
- useInitApp에서 사용하는 변수와 state를 적절히 추상화하여 동작에 따라 파일을 분리했습니다.
- supabase config에서 관리하는 점검 중 등의 상태를 초기 로딩에서만 가져와 점검 중일 때, 유저의 점검중 상태가 즉시 업데이트되지 않는 문제가 있었습니다.
- 이를 해결하기 위해 supabase config를 가져오는 API를 AppState가 foreground일 때 refetch해오도록 구현했습니다.
close #488
=> [RN-78] 앱 초기 로딩시간 개선

src/services/device.ts, src/services/notification.ts, src/services/user.ts
- DeviceService의 메서드들의 동작을 수정했습니다.
- iOS: fcm token을 가져오기 이전의 setAPNSToken 로직을 삭제했습니다.
- 기존: 로그인 또는 회원가입시 항상 device 정보를 새롭게 POST합니다.
- 변경: os와 model이 같다면 POST대신 가장 최신의 정보를 찾아 PATCH하도록 수정했습니다.
- refactor: local과 server의 device info를 비교하는 로직을 `synchronizeDeviceInfo()` 메서드로 분리했습니다.
close #490
=> [RN-79] Device API 관련 동작 수정

src/configs/toast/toastMessageProps.tsx, src/screens/uoslife_life/UoslifeLifeScreen.tsx
- 포털 연동을 완료한 유저만 시대팅 신청 가능하도록 변경했습니다.
- 포털 연동하지 않은 유저일 경우, 포털 연동 안내 문구와 함께 포털 연동 화면을 보여줍니다.
close #493
=> [RN-81] 포털 연동을 완료한 유저만 시대팅 신청 가능하도록 변경 #493

src/features/library/components/molecules/LibraryEventBox.tsx, src/features/library/components/molecules/LibraryUsageHistory.tsx
- 도서관 이용내역 시간 표기를 `시간/분`으로 변경했습니다.
- 도서관 기록 페이지의 ui를 일부 수정했습니다.(제목과 버튼 사이 간격 조정)
- 도서관 이용내역 확인에서 유저가 졸업생일 경우 표시 로직을 변경했습니다.
- 기존: `서버의 문제이거나 졸업생이면 확인할 수 없어요.` 표시
- 변경: 졸업생인 경우 `졸업생이면 확인할 수 없어요.`, 서버 문제의 경우 `서버의 문제일 수 있어요. 잠시 후 다시 시도해주세요.` 표시
close #513
=> [RN-89] 도서관 이용내역 시간 표기 변경

src/App.tsx, src/hooks/useDoubleBackPress.android.ts, src/hooks/useDoubleBackPress.ios.ts
- Android에서 뒤로가기를 두번 클릭시 앱이 종료되도록 동작을 개선했습니다.
- iOS의 경우 빈 함수가 실행되도록 구현해, Android에서만 `useDoubleBackPress` 훅이 호출되도록 구현했습니다..
- `.android`, `.ios` 파일을 찾지 못하는 typescript 오류가 있어 해당 부분 우선적으로 `@ts-expect-error`를 사용하였고, 추후 수정이 필요합니다.
close #500
=> [RN-83] Android 뒤로가기 동작 개선

src/features/library/services/library.ts
- librarySeatStartTime, libraryUsingStatus 변수를 getter 함수가 아닌 직접 storage에서 가져오도록 수정했습니다.
close #549
=> [RN-104] 도서관 이용시간 알림 기능 개선

src/features/uos_lifestyle/academic_calendar/components/Checkbox.tsx
- 공지사항 Item에서 사용할 Checkbox 컴포넌트를 제작하였습니다.
- 체크되지 않았을 때 <img width="23" alt="image" src="https://github.com/uoslife/uoslife-client/assets/81912837/bf79b326-5a13-4788-8b30-bae93fdb832e"> 
- 체크 했을 때 <img width="20" alt="image" src="https://github.com/uoslife/uoslife-client/assets/81912837/6ab2841b-e520-4097-a82a-9a63ce1e1c15">
=> [tf-academic-calendar-39] Checkbox 컴포넌트 제작

src/features/uos_lifestyle/academic_calendar/components/FilterButtonGroup.tsx, src/features/uos_lifestyle/academic_calendar/constants.ts, src/features/uos_lifestyle/academic_calendar/navigators/AcademicCalendarStackNavigator.tsx, src/features/uos_lifestyle/academic_calendar/screens/AcademicCalendarScreen.tsx, src/features/uos_lifestyle/academic_calendar/screens/AcademicCalendarSearchScreen.tsx, src/features/uos_lifestyle/academic_calendar/types/AcademicCalendar.ts, src/navigators/RootStackNavigator.tsx
- 학사일정 검색 페이지 추가
- 스택 네비게이션 설정(navigator 폴더 및 파일 추가)
- 학사일정 스크린에서 돋보기 클릭시 학사일정 검색 스크린으로 네비게이션
- 학사일정 검색 스크린에서 SearchInput컴포넌트 적용
- 필터 구분하는 상수 추가
+++++
- Camel case와 Snake case 혼종되어있는 것 수정
- 검색시 동작은 현재까지 미구현
- 
close #ISSUE
=> [tf-academic-calendar-38] 학사일정 페이지 추가

src/features/uos_lifestyle/academic_calendar/components/ScheduleItem.tsx
- 알림설정 활성화시간 시작일 09시 이전으로 수정
- today : UTC기준 현재시간
- standardDate : 일정 시작일 00시
- 한국 기준으로 해서 시차(9시간)와 일정시작시간(오전9시) 고려해서 flag>0이면 비활성화 
->사용자의 location에 따라 동적으로 시간 계산하여 활성화 여부 결정하도록 수정
close #ISSUE
=> [tf-academic-calendar-53] 알림설정 활성화시간 수정

src/api/core/customError.ts, src/api/core/methods.ts, src/api/services/type.ts, src/utils/api.ts
- API 응답값이 json이 아닌 경우 발생하는 오류(**iOS 앱의 process가 종료되는 현상**)를 해결했습니다.
- 서버에서 오는 응답의 `Content-Type`이 `application/json`이 아닌 경우 response.json()대신 .text() 함수를 호출하도록 수정했습니다.
- method.ts 파일 내에 작성되었던 CustomError 객체와, util 함수, type 선언 등을 각 파일로 분리했습니다.
close #587
=> [RN-111] API 응답시 처리 수정

src/configs/api.ts
- 서버 api url 환경을 개발 환경에서 선택할 수 있도록 변경했습니다.
- 기존 사용하던 `__DEV__` 변수대신, `src/configs/api.ts`파일의 `ENABLE_ALPHA_API_SERVER` 변수를 이용해 api url 환경을 선택할 수 있도록 수정했습니다.
close #589
=> [RN-113] 서버 api url 환경을 개발 환경에서 선택할 수 있도록 변경
