src/configs/toast/toastMessageProps.tsx, src/screens/StudentIdScreen.tsx
- 기능 오류로 비활성화 되어있던 학생증 QrCode를 활성화합니다.
- close #318
=> [APP-270] 학생증 QR 활성화

src/components/molecules/screens/main/contents/CafeteriaContents.tsx, src/hooks/useRefreshOnFocus.ts
- 메인페이지에서 학식 API를 불러오는 경우 React Query를 적용했습니다.
- mealTime 시간에 따라 시간이 변경는 경우(BREAKFAST > LUNCH), API를 재호출하도록 로직을 개선했습니다.
close #300
=> [APP-260] 메인페이지 학식 호출 로직 개선

src/navigators/MyPageStackNavigator.tsx, src/navigators/RootStackNavigator.tsx, src/screens/account/common/SetNicknameScreen.tsx, src/screens/account/signIn/VerificationScreen.tsx, src/screens/myPage/MypageMainScreen.tsx, src/screens/myPage/profile/MypageProfileScreen.tsx
- 혼재되어있던 'MyPage' 변수명을 'Mypage'로 통일했습니다.
close #331
=> [APP-275] 변수명 'MyPage'를 'Mypage'로 통일

README.md
- 시대생팀 uoslife-client의 리드미를 작성했습니다.
close #263
=> [APP-238] Readme 작성

ios/firebase/alpha/GoogleService-Info.plist, ios/uoslife.xcodeproj/project.pbxproj, ios/uoslife/AlphaInfo.plist, package.json
- codepush 배포환경에 mandatory 옵션을 추가했습니다.
- iOS 개발환경에서 alpha 환경을 사용할 수 있도록 환경설정을 수정했습니다.
close #340
=> [APP-279] iOS alpha 개발환경 설정 #340

src/api/services/core/libraryHistory/libraryHistoryAPI.interface.ts, src/api/services/core/libraryHistory/libraryHistoryAPI.ts, src/api/services/core/libraryHistory/libraryHistoryAPI.type.ts, src/services/utility.ts
- 도서관 이용내역이 업데이트되지 않은 문제를 '.../save' API를 같이 가져오도록 수정하여 해결했습니다.
close #339
=> [RN-1] 도서관 이용내역 새로고침 기능 수정

babel.config.js
- babel.config 파일의 react-native-reanimated/plugin의 위치를 수정했습니다.
#351
=> [RN-7] react-native-reanimated/plugin 에러

src/services/utility.ts
- 도서관 이용내역 save API의 endpoint params을 수정했습니다.(2023 > 2024)
close #357
=> [RN] 도서관 이용내역 API endpoint 수정

src/screens/thirdTab/RedirectLibraryRecapScreen.tsx
- 일부 기기에서 도서관 여정 화면이 잘리는 [현상](https://uoslifeteam.slack.com/archives/C05SYCN33NE/p1712152086335829)을 해결했습니다.
close #364
=> [RN-14] 일부 기기에서 도서관 여정 화면이 잘리는 현상

babel.config.js, src/App.tsx, src/components/animations/pressable_icon/AnimatePress.tsx
- moti를 이용해 버튼 애니메이션을 적용합니다.
close #375
=> [RN-22] 버튼 애니메이션 추가

src/components/molecules/screens/announcement/list/ArticleList.tsx, src/components/molecules/screens/announcement/main/MainArticleList.tsx, src/navigators/RootStackNavigator.tsx
- 공지사항 페이지에서 끌어당겨 새로고침 기능을 추가했습니다.
- react-query를 이용해 끌어당겨 새로고침 기능을 구현했습니다.
close #372
=> [RN-19] 공지사항 새로고침 기능 추가

src/components/molecules/screens/main/mainServiceBox/MainServiceBox.tsx, src/configs/deepLinking.ts, src/navigators/LibraryStackNavigator.tsx, src/navigators/RootStackNavigator.tsx, src/navigators/types/library.ts, src/screens/library/LibraryChallengeScreen.tsx, src/screens/library/LibraryMainScreen.tsx, src/screens/library/LibraryRankingScreen.tsx, src/screens/library/room_status/LibraryRoomStatusScreen.tsx, src/screens/library/room_status/LibrarySeatListScreen.tsx
- 도서관 예약 및 기록 기능에 맞춰 navigation stack의 구조를 추가하거나 변경했습니다.
- 새로운 Library 화면의 screen 컴포넌트를 추가했습니다.
- navigation 구조에 맞게 deeplink url을 추가했습니다.
close #374
=> [RN-21] 도서관 Navigation stack 구조 수정

src/screens/library/main_screen/MySeatScreen.tsx
- 내자리 > 좌석 연장하기 UI 구현을 완료하였습니다
- 좌석 연장하기 버튼을 눌렀을 때 모달이 나오도록 구현하였습니다
- api 연결 후에 각 상황별 toast가 추가되어야 합니다
- 반납하기 PR에 작성하였듯이, 버튼 text color의 수정을 위해 Button 컴포넌트를 수정해야 하는지 궁금합니다
=> [RN-32] 내자리 > 좌석 연장하기 UI 구현

src/screens/thirdTab/EventScreen.tsx
- 날짜 폰트를 수정하였습니다.
- 본문 워딩과 줄바꿈을 수정하였습니다.
- SE 기종에서 버튼이 Bottom Navigation에 가려지는 현상이 발생해 bottom 여백을 추가하였습니다.
=> [RN-44] 이벤트 페이지 디자인 수정사항 반영

src/screens/MainScreen.tsx, src/screens/mypage/MypageAppInformationScreen.tsx
- 마이페이지 > 앱 정보 페이지의 '현재 앱 버전'에 codepush 버전도 추가했습니다.
close #396
=> [RN-33]앱 버전에 codepush 버전 추가

src/screens/library/LibraryRankingScreen.tsx
- 도서관 순위 페이지에서 월간 순위 탭을 추가했습니다.
close #428
=> [RN-48] 도서관 순위에서 월간 순위 추가

src/components/molecules/screens/main/contents/AnnounceContents.tsx, src/screens/MainScreen.tsx
- 공지사항 content에서 응답값이 없는 경우 메인화면이 뜨지 않는 현상을 수정했습니다.
close #397
=> [RN-34] 메인화면이 뜨지 않는 현상

android/app/build.gradle, ios/uoslife.xcodeproj/project.pbxproj, package.json
- iOS, Android의 버전을 2.0.1로 업데이트했습니다.
close #434
=> [RN-50] 플랫폼 별 버전 업데이트

src/configs/analytics.ts, src/screens/library/room_status/LibrarySeatingChartScreen.tsx, src/screens/library/useLibraryExtend.ts, src/screens/library/useLibraryReturn.ts
- 도서관 예약, 연장, 반납 성공시 google analytics logging을 하도록 구현했습니다.
close #436
=> [RN-51] 도서관 API 요청 성공시 Google Analytics logging

src/api/core/client.ts, src/api/core/methods.ts, src/api/services/account/auth/authAPI.interface.ts, src/api/services/account/auth/authAPI.ts, src/api/services/account/auth/authAPI.type.ts, src/api/services/account/index.ts, src/api/services/account/type/index.ts, src/api/services/account/user/userAPI.interface.ts, src/api/services/account/user/userAPI.ts, src/api/services/account/user/userAPI.type.ts, src/api/services/account/verification/verificationAPI.interface.ts, src/api/services/account/verification/verificationAPI.ts, src/api/services/account/verification/verificationAPI.type.ts, src/configs/api.ts
- 계정 서비스에 해당하는 API URL과 사용 함수, 타입을 선언했습니다.
close #442
=> [RN-55] 계정 서비스 API 작성

src/services/utility.ts
- 도서관 예약이 기존 예약과 다른 예약이면, 새로운 ActivityKit을 활성화하도록 로직을 수정했습니다.
- storage에 저장되어있던 `isActivateLibraryDynamicIsland` 변수를 `librarySeatStartTime`으로 교체하고, 이를 서버 응답값과 비교하는 방식으로 구현했습니다.
close #461
=> feat: 도서관 Dynamic Island 로직 수정

src/services/device.ts
- device 정보를 PATCH시 os, model 프로퍼티를 전송하여 발생하는 에러를 해결합니다.
close #468
=> [RN-68] device 정보 PATCH시 발생하는 오류 해결

src/screens/uoslife_life/UoslifeLifeScreen.tsx
- Android 환경에서 시대팅 접근시 웹으로 redirect하도록 수정했습니다.
close #478
=> [RN-73] 시대팅 Andoird 접근시 웹으로 redirect

src/configs/toast/toastMessageProps.tsx, src/screens/MainScreen.tsx, src/screens/uoslife_life/CheckGradeScreen.tsx, src/screens/uoslife_life/UoslifeLifeScreen.tsx
- 숨은 학점 서비스 접근시, `숨은 학점은 기말고사 이후 확인할 수 있어요.` 문구를 추가했습니다.
close #481
=> [RN-73] 숨은 학점 서비스 안내문구 추가

src/hooks/useInitApp.ts
- 로그인 유지가 되지 않는 현상을 수정했습니다.
- 앱 최초 로딩시 refresh token을 이용하여 access token을 재발급하는 과정을 추가했습니다.
close #485
=> [RN-77] 로그인 유지가 안되는 현상 수정

src/App.tsx
- App에서 codepush를 감싸도록 수정했습니다.
=> App에서 codepush를 감싸도록 수정

src/configs/deeplink/deepLinking.ts, src/features/uos_lifestyle/academic_calendar/AcademicCalendarScreen.tsx, src/features/uos_lifestyle/components/screens/UosLifestyleScreen.tsx, src/navigators/RootStackNavigator.tsx, src/navigators/types/rootStack.ts
=> [tf-academic-calendar-22] 학사일정 페이지 제작

src/features/uos_lifestyle/graduate_credit/components/SubjectDetailButton.tsx, src/features/uos_lifestyle/graduate_credit/components/screens/GraduateCreditScreen.tsx
- 학과, 과목 정보 버튼 컴포넌트 제작했습니다.
- 디자인 시스템 최대한 이용해보려고 했는데 버튼 내부 글자 속성 바꾸기 실패했습니다..
close #ISSUE
=> [tf-graduate-credit-10] 버튼 컴포넌트 제작

index.js
- 해당 issue를 참고하여 iOS에서 백그라운드 상태일 때 알림이 오지 않는 현상을 해결했습니다.
close #512
=> [RN-88] iOS 백그라운드 알림이 안오는 현상

src/features/uos_lifestyle/graduate_credit/components/ProgressBar.tsx, src/features/uos_lifestyle/graduate_credit/components/SubjectDetailButton.tsx, src/features/uos_lifestyle/graduate_credit/components/dummydata.ts, src/features/uos_lifestyle/graduate_credit/components/screens/GraduateCreditScreen.tsx, src/features/uos_lifestyle/graduate_credit/configs/constants.ts, src/features/uos_lifestyle/graduate_credit/configs/dummydata.ts, src/features/uos_lifestyle/graduate_credit/services/creditService.ts, src/features/uos_lifestyle/graduate_credit/types.ts
- 과목 버튼별 ui 제작했습니다
- label 이용해서 props 사용 가능
- dummydata 파일 만들어서 테스트 진행했습니다.
- 최대한 가독성 높이려고 짜봤습니다
close #ISSUE
=> Feature/tf graduate credit 26: 과목별 버튼 ui 제작

src/features/uos_lifestyle/graduate_credit/components/ProgressBar.tsx, src/features/uos_lifestyle/graduate_credit/components/SubjectDetailButton.tsx, src/features/uos_lifestyle/graduate_credit/components/screens/CreditDetailScreen.tsx, src/features/uos_lifestyle/graduate_credit/components/screens/GraduateCreditScreen.tsx, src/features/uos_lifestyle/graduate_credit/configs/constants.ts, src/features/uos_lifestyle/graduate_credit/services/creditService.ts
- 페이지 ui 하드코딩
-
-
close #ISSUE
=> feature/tf-graduate-credit-31 페이지 ui 제작

src/features/uos_lifestyle/academic_calendar/constants.ts, src/features/uos_lifestyle/academic_calendar/screens/AcademicCalendarScreen.tsx
- 폴더 구조 변경
- screens, types, components 폴더 생성
- constants.ts 파일 생성
- 빈 폴더 올리기 위해 .gitkeep 파일 생성함. merge 후 삭제 요망
=> chore: 폴더 구조 변경

src/components/molecules/common/carousel/Carousel.tsx
- Android 환경에서 Carousel 모서리가 둥글게 나타나지 않는 현상을 수정했습니다.
close #531
=> [RN-95] Android에서 Carousel 모서리를 둥글게 변경

src/hooks/useInitApp.ts
- 도서관 이용시간 알림 기능이 실행되지 않는 현상을 수정했습니다.
- 기능 업데이트 후 mmkv의 `isLibraryStateActivity` key를 사용하지 않는다면 초기화되지 않기에, 아래 코드에서 항상 falsy로 판단되어 알림이 표시되지 않았습니다.
```typescript
// LibraryServices
if (isLibraryStateActivity) this.startLibraryStateActivity(response);
```
- 앱 초기 실행 단계(useInitApp)에서 storage에 `isLibraryStateActivity` key가 없는 경우 `true`로 초기화하도록 수정했습니다.
close #545
=> [RN-102] 도서관 이용시간 알림 기능이 실행되지 않는 현상

src/hoc/ErrorBoundary.tsx
- 사용하지 않는 Errorboundary 코드를 주석처리했습니다.
close #551
=> [RN-105] Errorboundary 코드 주석처리

src/api/core/methods.ts
- method.ts에 put 추가
- 우리 api에 put이 존재해서 method.ts에 put 추가
close #ISSUE
=> [tf-academic-calendar-40] api에 put 메소드 추가

src/configs/api.ts, src/features/uos_lifestyle/academic_calendar/api/academicCalendar.ts, src/features/uos_lifestyle/academic_calendar/api/academicCalendarAPI.interface.ts, src/features/uos_lifestyle/academic_calendar/api/academicCalendarAPI.type.ts, src/features/uos_lifestyle/academic_calendar/api/index.ts, src/features/uos_lifestyle/academic_calendar/types/schedule.type.ts
- api 중에서 [GET] 메소드를 사용하는 것들을 개발하였습니다.
- alpha에서 개발을 진행하기에 api 주소를 변경해놓은 상태입니다. main에 머지하기 전에 수정하는 작업이 필요합니다.
- 사용 예시는 다음과 같습니다.
=> feat: [GET] api 개발

src/configs/api.ts
- dev 모드에서 api url을 alpha로 변경했습니다.
close #566
=> [RN-107] dev 모드에서 api url을 alpha로 변경

src/configs/toast/toastMessageProps.tsx, src/features/uos_lifestyle/academic_calendar/components/ScheduleItem.tsx, src/features/uos_lifestyle/academic_calendar/screens/AcademicCalendarScreen.tsx
- 클립보드 복사 형식 수정 ✅
- 토스트 메세지 추가 ✅
- 모든 일정 탭 선택 시에만 검색 아이콘 등장하도록 수정 ✅
- 내 일정 편집 버튼 수정 ✅
- 내림차순 api에 반영되었는지 확인 ✅
=> [tf-academic-calendar-49] QA 수정사항 반영

src/api/core/methods.ts, src/features/uos_lifestyle/academic_calendar/components/ScheduleItem.tsx, src/features/uos_lifestyle/academic_calendar/screens/AcademicCalendarScreen.tsx
- 일정 삭제 시 모달 구현
- 일정이 없을 때 메세지 추가 
- 지난 일정 알림 비활성화(회색 아이콘)
- put 몌소드 변경
=> [tf-academic-calendar-50] QA 수정사항 반영

src/api/core/methods.ts, src/features/uos_lifestyle/academic_calendar/api/academicCalendar.ts, src/features/uos_lifestyle/academic_calendar/api/academicCalendarAPI.interface.ts, src/features/uos_lifestyle/academic_calendar/components/ScheduleItem.tsx, src/features/uos_lifestyle/academic_calendar/screens/AcademicCalendarScreen.tsx
- put, delete 메소드 response 없을 때 에러 수정
- 알람 비활성화 시 에러 수정
=> [tf-academic-calendar-51] alpha 배포 에러 수정

src/api/core/methods.ts, src/features/uos_lifestyle/academic_calendar/api/academicCalendar.ts, src/features/uos_lifestyle/academic_calendar/api/academicCalendarAPI.interface.ts
=> [tf-academic-calendar-51] NSNull 에러 핸들링

src/api/services/core/graduateCredit/graduateCreditAPI.type.ts, src/components/molecules/common/header/Header.tsx, src/features/uos_lifestyle/graduate_credit/components/LoadingIndicator.tsx, src/features/uos_lifestyle/graduate_credit/components/SubjectDetailButton.tsx, src/features/uos_lifestyle/graduate_credit/components/screens/CreditDetailScreen.tsx, src/features/uos_lifestyle/graduate_credit/components/screens/GraduateCreditScreen.tsx, src/features/uos_lifestyle/graduate_credit/configs/constants.ts, src/features/uos_lifestyle/graduate_credit/navigators/GraduateCreditStackNavigator.tsx, src/features/uos_lifestyle/graduate_credit/navigators/types/graduateCredit.ts, src/features/uos_lifestyle/graduate_credit/services/creditService.ts, src/features/uos_lifestyle/graduate_credit/types.ts
- 교양 학점 api 변경에 따른 화면 최신화
- 교양 선택 페이지에서 미이수 세부 정보 버튼 태그 뜨지 않던 문제 해결
- 교양 선택 페이지에서 프로그레스바내 최소이수학점 == 교양 최소 이수 학점 - 교양 필수 학점
close #ISSUE
=> [tf-graduate-credit-36] 교양 세부 페이지 수정

src/configs/analytics/analytics.ts, src/features/uos_lifestyle/academic_calendar/components/ScheduleItem.tsx, src/features/uos_lifestyle/academic_calendar/screens/AcademicCalendarScreen.tsx
1. 학사 일정 관리 페이지 도달 수 ✅
2. 텍스트 복사 기능 이벤트 수 ✅
3. 담기 기능 이벤트 수 ✅
4. 알림 설정 이벤트 수 ✅
페이지 도달과 기능 이벤트 사용 정도를 로깅할 수 있도록 GA를 연결하였습니다.
=> [tf-academic-calendar] GA 연결

src/configs/deeplink/deepLinking.ts
- `graduate_credit`를 deeplink screens에 추가했습니다.
close #585
=> [RN-110] tf 서비스 deeplink 대응

android/app/build.gradle, ios/uoslife.xcodeproj/project.pbxproj, ios/uoslife/Info.plist
- iOS와 Android의 버전을 업데이트하고, 배포에 대응했습니다.
- iOS: `2.0.3` > `2.0.4`
- Android: `2.0.2` > `2.0.3`
close #590
=> [RN-114] 앱 버전 업데이트

ios/fastlane/Fastfile, ios/uoslife.xcodeproj/project.pbxproj, ios/uoslife/Info.plist, src/configs/api.ts
- fastlane slack url 을 변경하고, testflight에 배포하여 project bundle version을 변경했습니다.
- `ENABLE_API_SERVER` 변수를 false를 기본값으로 설정했습니다.
close #598
=> [RN-117] fastlane slack url 변경 및 배포

src/configs/analytics/analytics.ts, src/features/uos_lifestyle/components/screens/UosLifestyleScreen.tsx, src/features/uos_lifestyle/restaurant/RestaurantScreen.tsx, src/features/uos_lifestyle/restaurant/components/RestaurantListContainer.tsx, src/features/uos_lifestyle/restaurant/hooks/useRestaurantItem.ts, src/features/uos_lifestyle/restaurant/types/restaurant.type.ts
- 맛집 리스트 GA 서비스를 추가했습니다.
- 빌드가 계속 실패해 동작 여부를 확인하지 못했습니다. 확인 부탁드립니다.
=> [RN-116] 맛집 리스트 GA 서비스 추가
